# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-23 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temperatures',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temp_in', models.FloatField()),
                ('temp_out', models.FloatField()),
                ('temp_oil', models.FloatField()),
            ],
        ),
    ]
