# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-13 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='press_1',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('press_in', models.FloatField()),
                ('press_out', models.FloatField()),
                ('diff', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='press_2',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('press_in', models.FloatField()),
                ('press_out', models.FloatField()),
                ('diff', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='press_3',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('press_in', models.FloatField()),
                ('press_out', models.FloatField()),
                ('diff', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='press_4',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('press_in', models.FloatField()),
                ('press_out', models.FloatField()),
                ('diff', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='press_5',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('press_in', models.FloatField()),
                ('press_out', models.FloatField()),
                ('diff', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='press_6',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('press_in', models.FloatField()),
                ('press_out', models.FloatField()),
                ('diff', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='temp_1',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temp_in', models.FloatField()),
                ('temp_out', models.FloatField()),
                ('temp_oil', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='temp_2',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temp_in', models.FloatField()),
                ('temp_out', models.FloatField()),
                ('temp_oil', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='temp_3',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temp_in', models.FloatField()),
                ('temp_out', models.FloatField()),
                ('temp_oil', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='temp_4',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temp_in', models.FloatField()),
                ('temp_out', models.FloatField()),
                ('temp_oil', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='temp_5',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temp_in', models.FloatField()),
                ('temp_out', models.FloatField()),
                ('temp_oil', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='temp_6',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('temp_in', models.FloatField()),
                ('temp_out', models.FloatField()),
                ('temp_oil', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='temperatures',
        ),
    ]
